version: '3.7'

services:
    nginx-react:
      image: nginx:alpine
      container_name: ${CONTAINER_NAME}
      working_dir: /app
      restart: unless-stopped
      volumes:
        - ./app:/app
        - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      ports:
        - ${APP_PORT}:80